// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ZawpNumYPg6l2OYBxaPM5vfHl-9wmqE',
    appId: '1:803004900550:web:4a61e181910563fd3923c7',
    messagingSenderId: '803004900550',
    projectId: 'jogpeer-c7aba',
    authDomain: 'jogpeer-c7aba.firebaseapp.com',
    databaseURL: 'https://jogpeer-c7aba-default-rtdb.firebaseio.com',
    storageBucket: 'jogpeer-c7aba.appspot.com',
    measurementId: 'G-6M20CVKNMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhg4gL0jqsX4D-7hJyUlVCistdn993BEc',
    appId: '1:803004900550:android:84fb6b79b53656eb3923c7',
    messagingSenderId: '803004900550',
    projectId: 'jogpeer-c7aba',
    databaseURL: 'https://jogpeer-c7aba-default-rtdb.firebaseio.com',
    storageBucket: 'jogpeer-c7aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZFxBoPboETqdACVuD8iBoYpj78z3-e8c',
    appId: '1:803004900550:ios:9657d3c170f89dc93923c7',
    messagingSenderId: '803004900550',
    projectId: 'jogpeer-c7aba',
    databaseURL: 'https://jogpeer-c7aba-default-rtdb.firebaseio.com',
    storageBucket: 'jogpeer-c7aba.appspot.com',
    iosClientId: '803004900550-brnpk6ldjso154sbv5cetguia0ad3l7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZFxBoPboETqdACVuD8iBoYpj78z3-e8c',
    appId: '1:803004900550:ios:9657d3c170f89dc93923c7',
    messagingSenderId: '803004900550',
    projectId: 'jogpeer-c7aba',
    databaseURL: 'https://jogpeer-c7aba-default-rtdb.firebaseio.com',
    storageBucket: 'jogpeer-c7aba.appspot.com',
    iosClientId: '803004900550-brnpk6ldjso154sbv5cetguia0ad3l7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageManagementSystem',
  );
}
